### PR TITLE
fixed compatibility with nette 2.4

### PR DESCRIPTION
**Pull request by simPod**

### CODE REVIEW

**Comment by MasterOfZozo** [comment]
ping @fprochazka

**Comment by MasterOfZozo** [comment]
Maybe can add new maintainer, if you have no more time to maintain this package, @fprochazka ?

**Comment by MasterOfZozo** [comment]
#4 seems ok as it provides backward compatibility.

**Comment by simPod** [comment]
👍

**Comment by fprochazka** [comment]
@simPod do you want to maintain this package?

**Comment by simPod** [comment]
@fprochazka Do you have any maintenance guidlines?

**Comment by simPod** [comment]
Just came across my fork. How will we do it? Merge and? :)

**Comment by fprochazka** [comment]
@simPod By looking at [`v1.0`](https://github.com/Kdyby/HtmlValidatorPanel/blob/v1.0/composer.json) we can see that the `v1.0` is for Nette 2.3 (for Tracy 2.3 to be precise). This can be probably merged (if it fixes the problem), master should be changed to require Tracy 2.4 and new `v1.1` can be tagged, after build passes :)

**Comment by fprochazka** [comment]
@simPod I've invited you to the organization. If you need any help with maintaining, I'm tryting to be more active at Pehapkari slack - you can catch me in `#kdyby` channel ideally, but if I go silent for too long, I'm almost always online on FB messenger.

**Comment by simPod** [comment]
@fprochazka understood, thanks

**Pull request merged**
